### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by geoyee** [Samweli/isochrones#12]
Hello, I have a problems when I try to use this plugin in QGIS, can you help me 😃 . I tried the data provided by this repo, but it reported the same error.
THX! This is a great job 👍 .

QGIS-version: 3.16.11
PostGIS-version: 14
Isochrones-version: 0.1.1

![image](https://user-images.githubusercontent.com/71769312/148740278-3e06cc6d-98dc-45aa-89c3-81c5189306e5.png)

**Comment by geoyee** [comment]
I am sorry, this is error. I accidentally misspelled it.
![image](https://user-images.githubusercontent.com/71769312/148741193-eebd0ccb-c074-4180-94c8-22e472d1ac5b.png)

**Comment by Samweli** [comment]
Hi @geoyee, apologies for a late reply.
I see you are using QGIS version 3.16.11, the plugin is supported up to QGIS version 3.8. can you try with versions less than 3.8 and see if the error persists, thanks.

**Comment by Samweli** [comment]
@geoyee I have noticed that in the above screenshot, you are passing network table as `public.road` instead of `public.roads` this can be the cause for the resulting error. 
Also new plugin version that supports QGIS 3.1x and 3.2x versions has been released here https://plugins.qgis.org/plugins/isochrones/version/0.1.2, you can now upgrade the plugin using the QGIS plugin manager.

**Comment by geoyee** [comment]
thank you, i am sorry for a late reply. Your response was very helpful
